# Generated by Django 2.1.5 on 2019-08-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlep', models.TextField()),
                ('texttopp', models.TextField()),
                ('textbottmp', models.TextField()),
                ('textp', models.TextField()),
                ('textlinkp', models.TextField()),
                ('linkp', models.TextField()),
                ('ratepointp', models.CharField(max_length=10)),
                ('linktextbtnp', models.TextField()),
                ('colorp', models.CharField(max_length=50)),
                ('coverp', models.ImageField(upload_to='p/images/')),
                ('logop', models.ImageField(upload_to='p/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Postlive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlel', models.TextField()),
                ('texttopl', models.TextField()),
                ('textbottml', models.TextField()),
                ('textl', models.TextField()),
                ('textlinkl', models.TextField()),
                ('linkl', models.TextField()),
                ('ratepointl', models.CharField(max_length=10)),
                ('linktextbtnl', models.TextField()),
                ('colorl', models.CharField(max_length=50)),
                ('coverl', models.ImageField(upload_to='l/images/')),
                ('logol', models.ImageField(upload_to='l/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Postslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlesl', models.TextField()),
                ('texttopsl', models.TextField()),
                ('textbottmsl', models.TextField()),
                ('textsl', models.TextField()),
                ('textlinksl', models.TextField()),
                ('linksl', models.TextField()),
                ('ratepointsl', models.CharField(max_length=10)),
                ('linktextbtnsl', models.TextField()),
                ('colorsl', models.CharField(max_length=50)),
                ('coversl', models.ImageField(upload_to='sl/images/')),
                ('logosl', models.ImageField(upload_to='sl/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Posttop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlet', models.TextField()),
                ('texttopt', models.TextField()),
                ('textbottmt', models.TextField()),
                ('textt', models.TextField()),
                ('textlinkt', models.TextField()),
                ('linkt', models.TextField()),
                ('ratepointt', models.CharField(max_length=10)),
                ('linktextbtnt', models.TextField()),
                ('colort', models.CharField(max_length=50)),
                ('covert', models.ImageField(upload_to='t/images/')),
                ('logot', models.ImageField(upload_to='t/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Posttopsecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.TextField()),
                ('texttops', models.TextField()),
                ('textbottms', models.TextField()),
                ('texts', models.TextField()),
                ('textlinks', models.TextField()),
                ('links', models.TextField()),
                ('ratepoints', models.CharField(max_length=10)),
                ('linktextbtns', models.TextField()),
                ('colors', models.CharField(max_length=50)),
                ('covers', models.ImageField(upload_to='s/images/')),
                ('logos', models.ImageField(upload_to='s/images/')),
            ],
        ),
    ]
